2024-09-09 16:00:09,117 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\can\PycharmProjects\module12\tests_12_4.py", line 25, in test_run
    runner = rt.Runner(['runner2'])
  File "C:\Users\can\PycharmProjects\module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2024-09-09 16:00:09,117 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\can\PycharmProjects\module12\tests_12_4.py", line 15, in test_walk
    runner = rt.Runner('runner1', speed=-1)
  File "C:\Users\can\PycharmProjects\module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
